//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cellphones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public string salesID { get; set; }
        public Nullable<int> spenttotal { get; set; }
        public Nullable<System.DateTime> timespent { get; set; }
        public string OrderID { get; set; }
    }
}
